plugins { id 'com.android.application' }

android {
    namespace 'com.example.tendacontrol'
    compileSdk 35
    defaultConfig {
        applicationId 'com.example.tendacontrol'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '1.3'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release { minifyEnabled false }
    }
    lint { abortOnError false }
}

dependencies { implementation 'androidx.core:core:1.13.1' }
